### ISSUE TITLE
EventEmitter<T> incorrectly extends interface EventEmitter (0.12.0+)

### ISSUE THREAD

**Issue by michaelkrog** [maxnowack/signaldb#826]
I have a weird issue after upgrading from 0.11.0. It works fine in 0.11.0, but 0.12.1 and 0.13.0 fails.

When building my angular project I get this:
```
✖ Compiling with Angular sources in Ivy partial compilation mode.
node_modules/signaldb/dist/types/EventEmitter.d.ts:2:19 - error TS2430: Interface 'EventEmitter<T>' incorrectly extends interface 'EventEmitter'.
  Types of property 'emit' are incompatible.
    Type '<U extends keyof T>(event: U, ...args: Parameters<T[U]>) => boolean' is not assignable to type '(type: string | number, ...args: any[]) => boolean'.
      Types of parameters 'event' and 'type' are incompatible.
        Type 'string | number' is not assignable to type 'keyof T'.
          Type 'number' is not assignable to type 'keyof T'.
            Type 'number' is not assignable to type 'string | symbol'.

2 declare interface EventEmitter<T extends Record<string | symbol, any>> {
                    ~~~~~~~~~~~~
node_modules/signaldb/dist/types/EventEmitter.d.ts:6:15 - error TS2415: Class 'EventEmitter<T>' incorrectly extends base class 'EventEmitter'.

6 declare class EventEmitter<T> extends BaseEventEmitter {
                ~~~~~~~~~~~~
```

I have been trying to figure out why it occurs, because to me it seems there have been no changes to that file (signaldb/dist/types/EventEmitter.d.ts) since 0.11.0.

**Comment by michaelkrog** [comment]
Okay..  Seems al I had to do was to create an issue here to be a rubber duck to myself.

I had references to an older @types/node in my own project. Updating that fixed the issue.

**Comment by maxnowack** [comment]
Great to hear! I'm not that happy with the method I used to have a typed `EventEmitter`. Maybe I find another solution and can get rid of the current one completely

**Comment by michaelkrog** [comment]
I was wrong (has the 0.11.0 version installed by mistake). 😆

The issue persists, and I just can't grasp what the difference is. 
If I switch back and forth between 0.11.0 and 0.12.0, then **0.11.0 just works** and **0.12.0 gives the above error** when building my angular project.
I am uptodate with angular 18.1.3. 

🤔

**Comment by maxnowack** [comment]
I don't see a clear cause for the issue right now. Maybe it has something to do an update of `vite`, but I didn't found an indication for this in the [changelog](https://github.com/vitejs/vite/blob/v5.3.5/packages/vite/CHANGELOG.md).
However, as I'm unhappy with the current `EventEmitter` extension anyway, I think it's the right time to switch to an alternative solution.

**Comment by maxnowack** [comment]
I released some small changes and released them in `v0.14.0`. Please give it a try and see if it solves the issue 🙂

**Comment by michaelkrog** [comment]
Awesome how fast you did that. 😀

It stills fails though. But the error is different now:
```
✖ Compiling with Angular sources in Ivy partial compilation mode.
node_modules/signaldb/dist/types/EventEmitter.d.ts:3:5 - error TS2416: Property 'on' in type 'EventEmitter<Events>' is not assignable to the same property in base type 'EventEmitter'.
  Type '<K extends keyof Events>(event: K, listener: Events[K]) => this' is not assignable to type '(type: string | number, listener: Listener) => this'.
    Types of parameters 'event' and 'type' are incompatible.
      Type 'string | number' is not assignable to type 'keyof Events'.
        Type 'number' is not assignable to type 'keyof Events'.
          Type 'number' is not assignable to type 'string | symbol'.

3     on<K extends keyof Events>(event: K, listener: Events[K]): this;
      ~~
node_modules/signaldb/dist/types/EventEmitter.d.ts:4:5 - error TS2416: Property 'emit' in type 'EventEmitter<Events>' is not assignable to the same property in base type 'EventEmitter'.
  Type '<K extends keyof Events>(event: K, ...args: Parameters<Events[K]>) => boolean' is not assignable to type '(type: string | number, ...args: any[]) => boolean'.
    Types of parameters 'event' and 'type' are incompatible.
      Type 'string | number' is not assignable to type 'keyof Events'.
        Type 'number' is not assignable to type 'keyof Events'.

4     emit<K extends keyof Events>(event: K, ...args: Parameters<Events[K]>): boolean;
      ~~~~
```

**Comment by maxnowack** [comment]
> My version of @types/events is 3.0.3.

I think this is the culprit. [`@types/events`](https://www.npmjs.com/package/@types/events) is made for the npm package [`events`](https://github.com/browserify/events), not for the node implementation. The types for node are provided through `@types/node`. Just uninstall `@types/events` and you should be fine 🙂

**Comment by michaelkrog** [comment]
Yeah. It comes from a dependency though.. 😆
I must figure out a way to get rid of it.


Thx for your help.

**Comment by maxnowack** [comment]
You're welcome!
I still don't understand why there are npm packages with the same name as standard node packages. This causes a lot of really ugly bugs.
Is it maybe an option to remove usage of `@types/events` it in the dependency?

**Comment by michaelkrog** [comment]
Yeah.. It is messy with those duplicate specifications in different packages. 🤯

I managed to get rid of it in the dependency for testing purposes (one our own internal libraries) and have that just refer to @types/node as signaldb does.

I the Angular Project, however, I have to add @types/node as a type in tsconfig.json for it to work.

```
{
  "extends": "../../tsconfig.json",
  "compilerOptions": {
    "types": [
      "@angular/localize",
      "@types/node"
    ]
 }
```

**Comment by maxnowack** [comment]
Okay, great! 🙂
If you have the time, it would be awesome if you could provide a very simple example of how to use signaldb together with angular (like the existing todo examples). I could then also look deeper into the issue and try to solve it.
The last time I worked with angular dates back to v1, so I'm quite outdated with newer versions 😅

**Comment by michaelkrog** [comment]
@maxnowack I will find some time to add an Angular example.

**Comment by maxnowack** [comment]
Awesome! Thank you so much!
